dist: xenial
language: go
os:
  - linux

gobuild_args: ""


env:
  - TEST_TFDIR="../templates/icp-ce" TEST_TFVARS="terraform-small-subnet-example.tfvars"

script:
  - cd tests && bats .

before_install:
#  # Later we will want to figure out which template that changed and only change that
# - |
#     if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
#       TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
#     fi
#     ## Probably use this instead now: CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
#     git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/' || {
#       echo "Only docs were updated, stopping build process."
#       exit
#     }
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir -p ~/bin
  - mv /tmp/terraform ~/bin
  - chmod a+x ~/bin/terraform
  - export PATH="~/bin:$PATH"

script:
  - go test -v -timeout 120m -run TestTerraformICP ./test/
